names = {
    # understat: fpl
    'Cristiano Ronaldo': 'Cristiano Ronaldo dos Santos Aveiro',
    'Son Heung-Min': 'Heung-Min Son',
    'Raphinha': 'Raphael Dias Belloli',
    'Bruno Fernandes': 'Bruno Miguel Borges Fernandes',
    'Richarlison': 'Richarlison de Andrade',
    'Emile Smith-Rowe': 'Emile Smith Rowe',
    'Said Benrahma': 'Saïd Benrahma',
    'Bernardo Silva': 'Bernardo Mota Veiga de Carvalho e Silva',
    'Gabriel Jesus': 'Gabriel Fernando de Jesus',
    'Rodri': 'Rodrigo Hernandez',
    'Martin Odegaard': 'Martin Ødegaard',
    'Jorginho': 'Jorge Luiz Frello Filho',
    'Rodrigo': 'Rodrigo Moreno',
    'Gabriel Martinelli': 'Gabriel Teodoro Martinelli Silva',
    'Philippe Coutinho': 'Philippe Coutinho Correia',
    'Fabinho': 'Fabio Henrique Tavares',
    'Gabriel': 'Gabriel Magalhães',
    'Eddie Nketiah': 'Edward Nketiah',
    'Juan Camilo Hernández': 'Juan Camilo Hernández Suárez',
    'Bruno Guimarães': 'Bruno Guimarães Rodriguez Moura',
    'Joelinton': 'Joelinton Cássio Apolinário de Lira',
    'Ben Chilwell': 'Benjamin Chilwell',
    'Fred': 'Frederico Rodrigues de Paula Santos',
    'Sergi Canos': 'Sergi Canós',
    'Thiago Silva': 'Thiago Thiago',
    'Emiliano Buendía': 'Emiliano Buendía Stati',
    'Rúben Neves': 'Rúben Diogo da Silva Neves',
    'João Pedro': 'João Pedro Junqueira de Jesus',
    'Fernandinho': 'Fernando Luiz Rosa',
    'N&#039;Golo Kanté': "N'Golo Kanté",
    'Oriol Romeu': 'Oriol Romeu Vidal',
    'Jonny': 'Jonathan Castro Otto',
    'Lucas Moura': 'Lucas Rodrigues Moura da Silva',
    'João Moutinho': 'João Filipe Iria Santos Moutinho',
    'Romain Saiss': 'Romain Saïss',
    'Douglas Luiz': 'Douglas Luiz Soares de Paulo',
    'Joe Willock': 'Joseph Willock',
    'Marc Guehi': 'Marc Guéhi',
    'Daniel Podence': 'Daniel Castelo Podence',
    'Trincão': 'Francisco Machado Mota de Castro Trincão',
    'Ferrán Torres': 'Ferran Torres',
    'Rúben Dias': 'Rúben Santos Gato Alves Dias',
    'Dele Alli': 'Bamidele Alli',
    'Raphael Varane': 'Raphaël Varane',
    'Thiago Alcántara': 'Thiago Alcántara do Nascimento',
    'João Cancelo': 'João Pedro Cavaco Cancelo',
    'Ricardo Pereira': 'Ricardo Domingos Barbosa Pereira',
    'Tanguy NDombele Alvaro': 'Tanguy Ndombele',
    'Nicolas Pepe': 'Nicolas Pépé',
    'Pedro Neto': 'Pedro Lomba Neto',
    'Valentino Livramento': 'Tino Livramento',
    'Mads Roerslev': 'Mads Roerslev Rasmussen',
    'Nuno Tavares': 'Nuno Varela Tavares',
    'Mohamed Elneny': 'Mohamed Naser El Sayed Elneny',
    'Kenedy': 'Robert Kenedy Nunes do Nascimento',
    'Alisson': 'Alisson Ramses Becker',
    'Asmir Begovic': 'Asmir Begović',
    'Samir': 'Samir Caetano de Souza Santos',
    'Alex Telles': 'Alex Nicolao Telles',
    'Allan': 'Allan Marques Loureiro',
    'Nicolas N&#039;Koulou': 'Nicolas Nkoulou',
    'Emiliano Martinez': 'Emiliano Martínez',
    'Kepa': 'Kepa Arrizabalaga',
    'Solly March': 'Solomon March',
    'Ederson': 'Ederson Santana de Moraes',
    'Lyanco': 'Lyanco Evangelista Silveira Neves Vojnovic',
    'Boubakary Soumare': 'Boubakary Soumaré',
    'Nathan Ferguson': 'Nathan Ferguson',
    'Oghenekaro Etebo': 'Oghenekaro Peter Etebo',
    'Samuel Kalu': 'Samuel Kalu ',
    'Imran Louza': 'Imrân Louza',
    'Diogo Dalot': 'José Diogo Dalot Teixeira',
    'Wesley': 'Wesley Moraes',
    'Jaden Philogene-Bidace': 'Jaden Philogene-Bidace',
    'David Raya': 'David Raya Martin',
    'Kristoffer Klaesson': 'Kristoffer Klaesson',
    'Bali Mumba': 'Bali Mumba',
    'Alejandro Garnacho': 'Alejandro Garnacho Ferreyra',
    'Chiquinho': 'Sonny Chiquinho',
    'Toti': 'Toti António Gomes',
    'Kayky': 'Kayky da Silva Chagas',
    'Zanka': 'Mathias Jorgensen',
    'Júnior Firpo': 'Héctor Junior Firpo Adames',
    'Josh Dasilva': 'Pelenda Joshua Dasilva',
    'Caglar Söyüncü': 'Çaglar Söyüncü',
    'Emerson': 'Emerson Aparecido Leite de Souza Junior',
    'André Gomes': 'André Filipe Tavares Gomes',
    'Hélder Costa': 'Hélder Wander Sousa de Azevedo e Costa',
    'Kiko Femenía': 'Francisco Femenía Far',
    'Trézéguet': 'Mahmoud Ahmed Ibrahim Hassan',
    'Nélson Semedo': 'Nélson Cabral Semedo',
    'José Sá': 'José Malheiro de Sá',

}
